// ============================================================
// performance.js — Performance Analyzer for StudyPath AI Pro
// ============================================================

// ── State ────────────────────────────────────────────────────
var allResults    = [];
var filterSubject = "all";
var filterLevel   = "all";
var sortMode      = "newest";
var unsubscribe   = null;

// ── Date Helper ──────────────────────────────────────────────
function addDaysToToday(days) {
  var d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().split("T")[0];
}

// ── Analysis Engine ──────────────────────────────────────────
function calculatePerformanceAnalysis(score, maxScore) {
  var pct = Math.round((score / maxScore) * 100);
  var level, priority, dailyTime, weeklyTime, taskCount, assignCount;

  if (pct < 50) {
    level = "Critical"; priority = "High";
    dailyTime = "60–90 min/day"; weeklyTime = "5–6 hours/week";
    taskCount = 5; assignCount = 3;
  } else if (pct < 70) {
    level = "Weak"; priority = "Medium";
    dailyTime = "45–60 min/day"; weeklyTime = "3–4 hours/week";
    taskCount = 3; assignCount = 2;
  } else if (pct < 85) {
    level = "Improving"; priority = "Low";
    dailyTime = "20–30 min/day"; weeklyTime = "1–2 hours/week";
    taskCount = 2; assignCount = 1;
  } else {
    level = "Strong"; priority = "Maintenance";
    dailyTime = "10–15 min/day"; weeklyTime = "Maintenance only";
    taskCount = 1; assignCount = 0;
  }

  return { percentage: pct, weaknessLevel: level, priority, recommendedDailyTime: dailyTime, recommendedWeeklyTime: weeklyTime, taskCount, assignCount };
}

function buildRecommendationText(topic, level) {
  if (level === "Critical")  return "You are weak in " + topic + ". Spend focused time daily and complete the generated assignments first.";
  if (level === "Weak")      return "You need more practice in " + topic + ". Follow the generated tasks this week.";
  if (level === "Improving") return "You are improving in " + topic + ". Keep practising consistently.";
  return "You are strong in " + topic + ". Do quick revision to maintain performance.";
}

// ── Task/Assignment Templates ────────────────────────────────
function buildGeneratedStudyTasks(result, resultId) {
  var topic   = result.topic;
  var subject = result.subject;
  var level   = result.weaknessLevel;
  var priority = result.priority;
  var templates = [];

  if (level === "Critical") {
    templates = [
      { title: "Revise fundamentals of " + topic, description: "Go back to basics and revise all core concepts of " + topic + ".", dueDate: addDaysToToday(1) },
      { title: "Complete 20 practice questions on " + topic, description: "Solve 20 practice problems covering " + topic + " to build familiarity.", dueDate: addDaysToToday(2) },
      { title: "Watch one focused lesson on " + topic, description: "Find a focused video lesson on " + topic + " and take notes.", dueDate: addDaysToToday(3) },
      { title: "Create short notes for " + topic, description: "Summarise key points of " + topic + " in your own words.", dueDate: addDaysToToday(4) },
      { title: "Take a mini test on " + topic, description: "Test yourself with a timed mini quiz on " + topic + " to check progress.", dueDate: addDaysToToday(5) },
    ];
  } else if (level === "Weak") {
    templates = [
      { title: "Revise weak concepts in " + topic, description: "Identify and revise the specific concepts you find difficult in " + topic + ".", dueDate: addDaysToToday(1) },
      { title: "Practice 15 questions on " + topic, description: "Solve 15 mixed-difficulty questions on " + topic + ".", dueDate: addDaysToToday(2) },
      { title: "Create a quick summary sheet for " + topic, description: "Write a one-page summary of important formulas/concepts for " + topic + ".", dueDate: addDaysToToday(3) },
    ];
  } else if (level === "Improving") {
    templates = [
      { title: "Review mistakes in " + topic, description: "Go over past mistakes and understand why each error happened in " + topic + ".", dueDate: addDaysToToday(1) },
      { title: "Practice 10 mixed questions on " + topic, description: "Practise 10 questions of varying difficulty on " + topic + ".", dueDate: addDaysToToday(2) },
    ];
  } else {
    templates = [
      { title: "Quick revision: maintain strength in " + topic, description: "Do a brief revision of " + topic + " to maintain your strong understanding.", dueDate: addDaysToToday(3) },
    ];
  }

  var now = firebase.firestore.FieldValue.serverTimestamp();
  return templates.map(function(t) {
    return Object.assign({}, t, {
      subject:       subject,
      topic:         topic,
      priority:      priority,
      status:        "pending",
      completed:     false,
      source:        "performance-auto",
      resultId:      resultId,
      autoGenerated: true,
      createdAt:     now,
      updatedAt:     now,
    });
  });
}

function buildGeneratedAssignments(result, resultId) {
  var topic   = result.topic;
  var subject = result.subject;
  var level   = result.weaknessLevel;
  var urgency = result.priority;
  var templates = [];

  if (level === "Critical") {
    templates = [
      { title: "Practice Assignment: " + topic + " Basics", description: "Complete a structured practice set covering the foundational concepts of " + topic + ".", deadline: addDaysToToday(3) },
      { title: "Application Assignment: " + topic + " Problem Solving", description: "Solve application-level problems that test your understanding of " + topic + ".", deadline: addDaysToToday(5) },
      { title: "Timed Test: " + topic, description: "Attempt a timed test on " + topic + " under exam conditions to build speed and accuracy.", deadline: addDaysToToday(7) },
    ];
  } else if (level === "Weak") {
    templates = [
      { title: "Practice Assignment: Strengthen " + topic, description: "Work through a set of practice questions to strengthen your grasp of " + topic + ".", deadline: addDaysToToday(3) },
      { title: "Mini Test: " + topic, description: "Take a short timed test on " + topic + " to check where you stand.", deadline: addDaysToToday(5) },
    ];
  } else if (level === "Improving") {
    templates = [
      { title: "Revision Assignment: Improve " + topic, description: "Complete a revision assignment targeting your weak points in " + topic + ".", deadline: addDaysToToday(3) },
    ];
  }
  // Strong → no assignments

  var now = firebase.firestore.FieldValue.serverTimestamp();
  return templates.map(function(t) {
    return Object.assign({}, t, {
      subject:       subject,
      topic:         topic,
      status:        "Pending",
      urgency:       urgency,
      priority:      urgency,
      source:        "performance-auto",
      resultId:      resultId,
      autoGenerated: true,
      createdAt:     now,
      updatedAt:     now,
    });
  });
}

// ── Skill Level Mapping ──────────────────────────────────────
function getSkillLevel(pct) {
  if (pct < 50) return "Beginner";
  if (pct < 70) return "Developing";
  if (pct < 85) return "Intermediate";
  return "Strong";
}

// ── Firestore Saves ──────────────────────────────────────────
async function savePerformanceResult(data) {
  var col = subColRef("performanceResults");
  if (!col) throw new Error("Not authenticated.");
  var now = firebase.firestore.FieldValue.serverTimestamp();
  var payload = Object.assign({}, data, { createdAt: now, updatedAt: now });
  var ref = await col.add(payload);
  return ref.id;
}

async function generateTasksForResult(result, resultId) {
  var tasks = buildGeneratedStudyTasks(result, resultId);
  var col   = subColRef("studyTasks");
  if (!col) return 0;
  var batch = db.batch();
  tasks.forEach(function(t) { batch.set(col.doc(), t); });
  await batch.commit();
  return tasks.length;
}

async function generateAssignmentsForResult(result, resultId) {
  var assignments = buildGeneratedAssignments(result, resultId);
  if (!assignments.length) return 0;
  var col = subColRef("assignments");
  if (!col) return 0;
  var batch = db.batch();
  assignments.forEach(function(a) { batch.set(col.doc(), a); });
  await batch.commit();
  return assignments.length;
}

async function upsertSkillFromResult(result) {
  var col = subColRef("skills");
  if (!col) return;
  var topic   = result.topic;
  var subject = result.subject;
  var pct     = result.percentage;
  var level   = getSkillLevel(pct);
  var now     = firebase.firestore.FieldValue.serverTimestamp();

  // Try to find existing skill by topic name (case-insensitive)
  var snap = await col.get();
  var existing = null;
  snap.docs.forEach(function(d) {
    var data = d.data();
    if (!existing) {
      var nameMatch  = data.name  && data.name.toLowerCase()  === topic.toLowerCase();
      var topicMatch = data.topic && data.topic.toLowerCase() === topic.toLowerCase();
      if (nameMatch || topicMatch) existing = d;
    }
  });

  if (existing) {
    await existing.ref.update({
      level:         level,
      progress:      pct,
      source:        "performance-auto",
      autoGenerated: true,
      updatedAt:     now,
    });
  } else {
    await col.add({
      name:          topic,
      subject:       subject,
      topic:         topic,
      category:      subject,
      level:         level,
      progress:      pct,
      source:        "performance-auto",
      autoGenerated: true,
      createdAt:     now,
      updatedAt:     now,
    });
  }
}

async function deletePerformanceResult(resultId) {
  var col = subColRef("performanceResults");
  if (!col) throw new Error("Not authenticated.");
  await col.doc(resultId).delete();
}

// ── Load & Render Results ────────────────────────────────────
function loadPerformanceResults() {
  var container = document.getElementById("perf-results-list");
  if (!container) return;

  if (unsubscribe) unsubscribe();
  container.innerHTML = buildSkeletonHTML();

  unsubscribe = listenToUserCollection("performanceResults", function(docs, err) {
    if (err) { container.innerHTML = '<p class="perf-empty-msg">Failed to load results.</p>'; return; }
    allResults = docs;
    renderPerformanceResults();
    populateSubjectFilter();
  }, { orderBy: "createdAt", orderDir: "desc" });
}

function renderPerformanceResults() {
  var container = document.getElementById("perf-results-list");
  if (!container) return;

  var filtered = allResults.slice();

  if (filterSubject !== "all") {
    filtered = filtered.filter(function(r) { return r.subject === filterSubject; });
  }
  if (filterLevel !== "all") {
    filtered = filtered.filter(function(r) { return r.weaknessLevel === filterLevel; });
  }

  if (sortMode === "lowest") {
    filtered.sort(function(a, b) { return (a.percentage || 0) - (b.percentage || 0); });
  } else {
    // newest first (default from Firestore listener)
    filtered.sort(function(a, b) {
      var ta = a.createdAt && a.createdAt.toMillis ? a.createdAt.toMillis() : 0;
      var tb = b.createdAt && b.createdAt.toMillis ? b.createdAt.toMillis() : 0;
      return tb - ta;
    });
  }

  if (!filtered.length) {
    container.innerHTML =
      '<div class="perf-empty">' +
        '<div class="perf-empty-icon">📊</div>' +
        '<p class="perf-empty-msg">' + (allResults.length ? "No results match your filters." : "No performance results yet.") + '</p>' +
        (!allResults.length ? '<p class="perf-empty-sub">Add a result to generate your first smart study plan.</p>' : '') +
      '</div>';
    return;
  }

  container.innerHTML = filtered.map(function(r) {
    return buildResultCard(r);
  }).join("");
}

function buildResultCard(r) {
  var pct      = r.percentage || 0;
  var lvl      = r.weaknessLevel || "—";
  var lvlCls   = weaknessBadgeClass(lvl);
  var date     = r.createdAt && r.createdAt.toDate ? formatDate(r.createdAt.toDate()) : "—";
  var tasksCnt = r.generatedStudyTaskCount || 0;
  var asnCnt   = r.generatedAssignmentCount || 0;
  var barColor = pct >= 85 ? "linear-gradient(90deg,#22c55e,#22d3ee)"
               : pct >= 70 ? "linear-gradient(90deg,#38bdf8,#8b5cf6)"
               : pct >= 50 ? "linear-gradient(90deg,#f59e0b,#38bdf8)"
               :              "linear-gradient(90deg,#ef4444,#f59e0b)";

  return '<div class="perf-result-card" id="perf-card-' + escHtmlP(r.id) + '">' +
    '<div class="perf-result-header">' +
      '<div>' +
        '<div class="perf-result-title">' + escHtmlP(r.subject) + ' — ' + escHtmlP(r.topic) + '</div>' +
        '<div class="perf-result-meta">' + date + (r.examDate ? ' &nbsp;·&nbsp; Exam: ' + escHtmlP(r.examDate) : '') + '</div>' +
      '</div>' +
      '<div style="display:flex;align-items:center;gap:.5rem;flex-shrink:0;">' +
        '<span class="badge ' + lvlCls + '">' + escHtmlP(lvl) + '</span>' +
        '<button class="btn btn-icon btn-danger btn-sm" onclick="handleDeleteResult(\'' + escHtmlP(r.id) + '\')" title="Delete result">🗑️</button>' +
      '</div>' +
    '</div>' +

    '<div class="perf-score-row">' +
      '<div class="perf-pct-big" style="color:' + pctColor(pct) + ';">' + pct + '%</div>' +
      '<div class="perf-score-detail">' +
        '<div>' + escHtmlP(String(r.score)) + ' / ' + escHtmlP(String(r.maxScore)) + '</div>' +
        '<div style="font-size:.75rem;color:var(--text-muted);">' + escHtmlP(r.recommendedDailyTime || "—") + ' &nbsp;·&nbsp; ' + escHtmlP(r.recommendedWeeklyTime || "—") + '</div>' +
      '</div>' +
    '</div>' +

    '<div class="progress-wrap" style="height:6px;margin:.5rem 0;">' +
      '<div class="progress-bar" style="width:' + pct + '%;background:' + barColor + ';"></div>' +
    '</div>' +

    (tasksCnt || asnCnt ?
      '<div class="perf-gen-row">' +
        (tasksCnt ? '<span class="perf-gen-badge">📚 ' + tasksCnt + ' task' + (tasksCnt !== 1 ? 's' : '') + ' generated</span>' : '') +
        (asnCnt  ? '<span class="perf-gen-badge">📋 ' + asnCnt  + ' assignment' + (asnCnt !== 1 ? 's' : '') + ' generated</span>'  : '') +
        '<span class="perf-gen-badge">🚀 Skill updated</span>' +
      '</div>' : '') +

    (r.notes ? '<div class="perf-result-notes">' + escHtmlP(r.notes) + '</div>' : '') +
  '</div>';
}

function weaknessBadgeClass(lvl) {
  if (lvl === "Critical")  return "badge-danger";
  if (lvl === "Weak")      return "badge-warning";
  if (lvl === "Improving") return "badge-primary";
  if (lvl === "Strong")    return "badge-success";
  return "badge-muted";
}

function pctColor(pct) {
  if (pct < 50) return "var(--danger)";
  if (pct < 70) return "var(--warning)";
  if (pct < 85) return "var(--primary)";
  return "var(--success)";
}

function populateSubjectFilter() {
  var select = document.getElementById("filter-subject");
  if (!select) return;
  var subjects = [];
  allResults.forEach(function(r) {
    if (r.subject && subjects.indexOf(r.subject) === -1) subjects.push(r.subject);
  });
  var current = select.value;
  select.innerHTML = '<option value="all">All Subjects</option>' +
    subjects.map(function(s) {
      return '<option value="' + escHtmlP(s) + '"' + (s === current ? ' selected' : '') + '>' + escHtmlP(s) + '</option>';
    }).join("");
  if (subjects.indexOf(current) !== -1) select.value = current;
}

// ── Analysis Result Card ─────────────────────────────────────
function showAnalysisResult(result, taskCount, assignCount) {
  var box = document.getElementById("analysis-result");
  if (!box) return;

  var pct   = result.percentage;
  var level = result.weaknessLevel;
  var rec   = buildRecommendationText(result.topic, level);

  box.innerHTML =
    '<div class="analysis-result-card">' +
      '<div class="analysis-result-header">' +
        '<div class="analysis-pct" style="color:' + pctColor(pct) + ';">' + pct + '%</div>' +
        '<span class="badge ' + weaknessBadgeClass(level) + ' badge-lg">' + level + '</span>' +
      '</div>' +
      '<p class="analysis-rec">' + escHtmlP(rec) + '</p>' +
      '<div class="analysis-detail-grid">' +
        '<div class="analysis-detail-item"><div class="analysis-detail-label">Daily Focus</div><div class="analysis-detail-val">' + escHtmlP(result.recommendedDailyTime) + '</div></div>' +
        '<div class="analysis-detail-item"><div class="analysis-detail-label">Weekly Target</div><div class="analysis-detail-val">' + escHtmlP(result.recommendedWeeklyTime) + '</div></div>' +
        '<div class="analysis-detail-item"><div class="analysis-detail-label">Tasks Created</div><div class="analysis-detail-val">' + taskCount + '</div></div>' +
        '<div class="analysis-detail-item"><div class="analysis-detail-label">Assignments Created</div><div class="analysis-detail-val">' + assignCount + '</div></div>' +
      '</div>' +
      '<div style="margin-top:.75rem;font-size:.78rem;color:var(--text-muted);">Skill tracker has been updated automatically.</div>' +
    '</div>';

  box.style.display = "block";
  box.scrollIntoView({ behavior: "smooth", block: "nearest" });
}

// ── Delete Handler ───────────────────────────────────────────
async function handleDeleteResult(id) {
  if (!confirm("Delete this performance result? The auto-generated tasks and assignments will remain, but you can delete them manually.")) return;
  try {
    await deletePerformanceResult(id);
    showSuccess("Performance result deleted.");
  } catch (err) {
    showError("Failed to delete. Please try again.");
    console.error("deletePerformanceResult error:", err);
  }
}

// ── Form Submit ──────────────────────────────────────────────
async function handlePerformanceSubmit(e) {
  e.preventDefault();

  var subject    = (document.getElementById("perf-subject").value || "").trim();
  var topic      = (document.getElementById("perf-topic").value   || "").trim();
  var scoreRaw   = document.getElementById("perf-score").value;
  var maxRaw     = document.getElementById("perf-max").value;
  var confidence = document.getElementById("perf-confidence").value;
  var examDate   = document.getElementById("perf-exam-date").value || null;
  var notes      = (document.getElementById("perf-notes").value   || "").trim();
  var errEl      = document.getElementById("perf-form-error");
  var btn        = document.getElementById("perf-submit-btn");

  // Validation
  errEl.textContent = "";
  clearFieldErrors();
  var valid = true;

  if (!subject) { setFieldError("perf-subject", "Subject is required."); valid = false; }
  if (!topic)   { setFieldError("perf-topic",   "Topic is required.");   valid = false; }

  var score    = parseFloat(scoreRaw);
  var maxScore = parseFloat(maxRaw);

  if (scoreRaw === "" || isNaN(score))                  { setFieldError("perf-score", "Score is required and must be a number.");       valid = false; }
  if (maxRaw  === "" || isNaN(maxScore) || maxScore <=0){ setFieldError("perf-max",   "Max Score must be a number greater than 0."); valid = false; }
  if (valid && score > maxScore)                        { setFieldError("perf-score", "Score cannot be greater than Max Score.");       valid = false; }
  if (!valid) return;

  var analysis = calculatePerformanceAnalysis(score, maxScore);

  var resultData = {
    subject:                   subject,
    topic:                     topic,
    score:                     score,
    maxScore:                  maxScore,
    percentage:                analysis.percentage,
    confidence:                confidence || "Medium",
    examDate:                  examDate,
    notes:                     notes,
    weaknessLevel:             analysis.weaknessLevel,
    priority:                  analysis.priority,
    recommendedDailyTime:      analysis.recommendedDailyTime,
    recommendedWeeklyTime:     analysis.recommendedWeeklyTime,
    generatedStudyTaskCount:   analysis.taskCount,
    generatedAssignmentCount:  analysis.assignCount,
    skillUpdated:              true,
    source:                    "manual-performance-entry",
  };

  showLoading(btn, "Analysing…");
  var analysisBox = document.getElementById("analysis-result");
  if (analysisBox) analysisBox.style.display = "none";

  try {
    // 1. Save the performance result
    var resultId = await savePerformanceResult(resultData);

    // 2. Generate study tasks
    var taskCount = await generateTasksForResult(resultData, resultId);

    // 3. Generate assignments
    var assignCount = await generateAssignmentsForResult(resultData, resultId);

    // 4. Upsert skill
    await upsertSkillFromResult(resultData);

    showSuccess("Analysis complete! Study plan generated.");
    showAnalysisResult(resultData, taskCount, assignCount);
    document.getElementById("perf-form").reset();
  } catch (err) {
    console.error("handlePerformanceSubmit error:", err);
    errEl.textContent = "Failed to save. Please check your connection and try again.";
  } finally {
    hideLoading(btn);
  }
}

// ── Field Error Helpers ──────────────────────────────────────
function setFieldError(fieldId, msg) {
  var el = document.getElementById(fieldId);
  if (el) el.classList.add("error");
  var errEl = document.getElementById(fieldId + "-error");
  if (errEl) errEl.textContent = msg;
}

function clearFieldErrors() {
  document.querySelectorAll(".perf-form-field.error, .form-control.error").forEach(function(el) {
    el.classList.remove("error");
  });
  ["perf-subject","perf-topic","perf-score","perf-max"].forEach(function(id) {
    var errEl = document.getElementById(id + "-error");
    if (errEl) errEl.textContent = "";
  });
}

// ── Skeleton ─────────────────────────────────────────────────
function buildSkeletonHTML() {
  var html = "";
  for (var i = 0; i < 3; i++) {
    html += '<div class="perf-result-card">' +
      '<div class="skeleton" style="height:1rem;width:55%;margin-bottom:.75rem;"></div>' +
      '<div class="skeleton" style="height:.75rem;width:35%;margin-bottom:.5rem;"></div>' +
      '<div class="skeleton" style="height:6px;width:100%;border-radius:4px;"></div>' +
    '</div>';
  }
  return html;
}

// ── Escape HTML ──────────────────────────────────────────────
function escHtmlP(str) {
  return String(str || "").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
}

// ── DOMContentLoaded Init ────────────────────────────────────
document.addEventListener("DOMContentLoaded", function() {
  initMobileToggleVisibility();
  initSidebarToggle();
  setActiveNav();

  var logoutBtn = document.getElementById("logout-btn");
  if (logoutBtn) logoutBtn.addEventListener("click", logoutUser);

  // Form submit
  var form = document.getElementById("perf-form");
  if (form) form.addEventListener("submit", handlePerformanceSubmit);

  // Filters
  var filterSubjectEl = document.getElementById("filter-subject");
  if (filterSubjectEl) filterSubjectEl.addEventListener("change", function() {
    filterSubject = this.value; renderPerformanceResults();
  });

  var filterLevelEl = document.getElementById("filter-level");
  if (filterLevelEl) filterLevelEl.addEventListener("change", function() {
    filterLevel = this.value; renderPerformanceResults();
  });

  var sortEl = document.getElementById("filter-sort");
  if (sortEl) sortEl.addEventListener("change", function() {
    sortMode = this.value; renderPerformanceResults();
  });

  // Auth check
  onAuthStateReady(async function(user) {
    if (!user) return;
    var profile = await getUserProfile();
    populateUserUI(user, profile);
    loadPerformanceResults();
  });
});
